### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by liadembin**
firstly, I would like to say how much I love this challenge. 
personally, I prefer not to use visual studio but rather Dotnet and I thought documenting the use of the Dotnet tool for the challenge would be helpful.

### CODE REVIEW

**Review by dr-vortex — COMMENTED** [review]
The .csproj file is critical to the project (with or without VS)

> This is the most important file in our application. It tells .NET how to build the project.
>
> All .NET projects list their dependencies in the .csproj file. If you have worked with JavaScript before, think of it like a package.json file. The difference is, instead of a JSON, this is an XML file. When you run dotnet restore, it uses this file to figure out which NuGet packages to download and copy to the project folder.
>
> The .csproj file also contains all the information that .NET tooling needs to build the project. It includes the type of the project being built (console, web, desktop, etc.), the platform this project targets and any dependencies on other projects or 3rd party libraries.

https://stackoverflow.com/a/65699364/17637456

**Comment by liadembin** [comment]
Sure,  maybe I missed it but I could find one, since an sln file was included I figured a  csproject file ought to be as well, am I missing something?(a reason not to include) I’m not well versed in the c# eco system since I mostly do web, python, and some lower level.

**Comment by dr-vortex** [comment]
@liadembin Your PR deletes the .csproj file

**Comment by liadembin** [comment]
my bad, sorry for bothering also, it seems that my suggestion to update the readme has already happened(). so I will close this request(https://github.com/SebLague/Chess-Challenge/issues/85)

**Pull request closed without merging**
