### PR TITLE
add resizable window feature

### PR DESCRIPTION
**Pull request by audiBookning**
When trying the build in my pitifully old and small laptop, i found that even the "small window" size was too big for it and couldn't even resize the window 😪
So here is a small refactor of the code to enable that feature. I think that i managed to maintain compatibility with the fixed sized window feature and there should be no problem with people that are using the previous code.

### CODE REVIEW

**Comment by dudecon** [comment]
Ran the code in Linux (Pop!_OS 22.04 LTS) and building in Visual Studio Code, where it crashes on line 18, because the window hasn't been created yet. I moved the call to line 29, which fixed it:
`
            Raylib.InitWindow(screenWidth, screenHeight, "Chess Coding Challenge");
            Raylib.SetTargetFPS(60);
            Raylib.SetWindowState(ConfigFlags.FLAG_WINDOW_RESIZABLE);`
However, on my computer, Raylib.GetScreenWidth() and Raylib.GetScreenHeight() have significant lag, which resulted in #177. This appears to have an effect here, with the result that the window size tends to "run away" from me. I don't see any easy fix, and this isn't impossible to work around, but is a bit janky.

The second thing I noticed is that the board and UI size is only based on window width, and disregards window height. That should probably be incorporated in UIHelper.cs in the Scale and ScaleInt functions as well as the UpdateCamera function where the zoom is set using only the width:
`
cam.zoom = screenWidth / 1280f * 0.7f;`

**Comment by audiBookning** [comment]
Thanks for the corrections.
My problem was more about the height so i was contented with it but you are right. The zoom should be adjusted as well.
The crash it didn't happen in in my windows machine. I wonder if it also happen in macOS?
As for the lag situation, i do not have access to a linux box at the moment so i cannot debug it.
Could it be because of driver issues?
I can add the corrections from #177. That PR and my own are only small changes after all. But on the other hand it might be better to wait for that other PR first since they are 2 separate issues?
I will leave this code here for reference and leave it open for a while until it is decided.
Or someone can take it and add other needed changes if they so which.

**Comment by dudecon** [comment]
PR #177 has already been merged, so your changes already incorporate it. I was just using it as an example of the Raylib.GetScreen... function causing problems. I'm not sure how widespread it is, if macOS encounters it, or even other Linux distros. It could also be, as you point out, a driver problem on my end.

I've implemented a fix for the UI scaling in PR #257. Hopefully that also works on your hardware!

**Comment by audiBookning** [comment]
> PR #177 has already been merged, so your changes already incorporate it

😓.  What can i say?
Maybe... People should not think they can miss their sleep without consequences?

I have to leave the computer but i managed to take a quick look at you PR.
You should consider separating your "resize" changes from the other code changes? I mean, i can see your "secret" MyBot.cs code and other changes mixed with it 😉

**Comment by dudecon** [comment]
Yeah, I tried to rebase the branch, but I haven't uncovered the arcane method of only including the changes that I want.

**Comment by dudecon** [comment]
Just created a new branch of my fork repo with only the changes I wanted. Thanks for the patience.

**Comment by audiBookning** [comment]
This is getting way out of the PR concerns and look more like a chat platform😀.
But since you already have made your PR clean i can close this one and will extend some of my opinions before that.
No need to "dirty" too much Sebastian repo 😋 But i think it is all in good intentions so he might look the other way this time.

Myself i usually dislike the whole git/github workflow. But it is just a temporary pain and git (or any other preferred version control ) is really essential for modern dev.
It is always good to take the time to study a little bit more about it. But more importantly, one should try to use it daily for any dev work. Even the simplest one or hobby work.
Constant practice is always the most trustworthy way to learn anything.

Here is the simplest workflow that i can think of to make a PR
- fork SebLague repo.
- clone your fork to your local machine
- create a branch of the main.
- Make your changes
- commit and push
- go to your fork in github and there should be a button/link to create a PR.

Git seems small but there are tons of weird commands that one uses only rarely for some very specific situations. Trying to remember it all is a tiresome job when one has so many other thing to constantly learn.
The important part in all of this is the habit of creating a branch when one wants to create some change to something. This habit will separate our code ideas into different branches than can be merged at will. Here one begins to see the real power of git. Future freedom and control.
For example: create a branch for your resize-window, another for you Mybot-mini-max, or another for your myBot-montecarlo-tree-search, etc This way one separate our concerns and avoid too much confusion.

If ones problem is that we want to only share some commits from a branch then one could use something like [cherry-pick](https://stackoverflow.com/questions/36778375/git-apply-a-commit-on-another-branch-to-the-working-copy).

I think you mentioned rebase? That is normally used to "squash" many commits into one. It has the advantage that you can clean the history of your commits. Many people makes many commits until they have something presentable and they don't like to "pollute" the original repo with the diary of all their little fights.

You could have also done a direct fork of my own repo. Repeat the whole process and then there is an option in github (at the top?) to indicate where you want to send the PR. In this case it would probably work fine, but in more complex and dynamic repo you might find some conflicts if my repo was behind in later commits from the original repo.

**Pull request closed without merging**
