### PR TITLE
[Move Generation] Use stack allocation instead of heap allocation.

### PR DESCRIPTION
**Pull request by TheBlackPlague**
# Summary

This PR serves as a fix for #188. It makes all necessary changes to allow users to use stack allocation for their move lists while maintaining the API in its current state wherever possible. While I believe other changes can be done to further speed up the API, they weren't the main objective of this PR and are left untouched wherever possible. 

Let me know your thoughts.

# Benchmarks

As requested, I ran the popular [PERFT](https://www.chessprogramming.org/Perft) on both versions of the PR. This is a very popular test for move generation correctness and performance benchmarking (and although it doesn't do justice to the issue since we will never reach a high enough depth in PERFT as we do in search due to pruning), I still felt as if it was reasonable to do and speed gains would be visible. As with all benchmarks, speedups may differ depending on hardware. It's why I noted down the hardware in the results below.

The results were:
```
Position: Starting Chess Position (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)
Depth: 7

Current Master:     Searched 3195901860 nodes in 39585ms (Speed: ~  80.7Mnps)
Stackalloc Changes: Searched 3195901860 nodes in 20856ms (Speed: ~ 153.2Mnps)
Speedup: ~ 1.87x speed of current master.

Hardware: i9-11900H
```

Before you think, "Not even 2x the speed," - do note that in the relevant issue, a depth over 17 was reached during QSearch. In this case, we're not hitting even a depth of 8 (since it would take too long due to a lack of pruning). The more you increase the depth, the bigger the speedup will be, increasing with respect to the branching factor.

For the test, the following configuration was run for the base version (current master)
```cs
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using ChessChallenge.Chess;
using Move = ChessChallenge.API.Move;

namespace ChessChallenge.My_Bot;

public class Perft
{

    public static void Run()
    {
        Board board = new();
        board.LoadStartPosition();

        const int depth = 7;
        
        Console.WriteLine($"Perft to depth {depth}...");
        
        ChessChallenge.API.Board apiBoard = new(board);

        ulong nodes = 0;
        nodes = Internal(apiBoard, depth - 5);
        nodes = Internal(apiBoard, depth - 4);
        nodes = Internal(apiBoard, depth - 3);
        
        Stopwatch watch = new();
        watch.Start();
        nodes = Internal(apiBoard, depth);
        watch.Stop();
        
        Console.WriteLine("Searched {0} nodes in {1}ms", nodes, watch.ElapsedMilliseconds);
    }

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    private static ulong Internal(ChessChallenge.API.Board board, int depth)
    {
        if (depth == 1)
            return (ulong)board.GetLegalMoves().Length;
        
        ulong nodes = 0;
        
        Move[] moves = board.GetLegalMoves();
        
        foreach (Move move in moves) {
            board.MakeMove(move);
            nodes += Internal(board, depth - 1);
            board.UndoMove(move);
        }
        
        return nodes;
    }

}
```
and an altered version, adhering to the changes in this PR was run for my changes:
```cs
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using ChessChallenge.Chess;

namespace ChessChallenge.My_Bot;

public class Perft
{

    public static void Run()
    {
        Board board = new();
        board.LoadStartPosition();

        const int depth = 7;
        
        Console.WriteLine($"Perft to depth {depth}...");
        
        ChessChallenge.API.Board apiBoard = new(board);

        ulong nodes = 0;
        nodes = Internal(apiBoard, depth - 5);
        nodes = Internal(apiBoard, depth - 4);
        nodes = Internal(apiBoard, depth - 3);
        
        Stopwatch watch = new();
        watch.Start();
        nodes = Internal(apiBoard, depth);
        watch.Stop();
        
        Console.WriteLine("Searched {0} nodes in {1}ms", nodes, watch.ElapsedMilliseconds);
    }

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    private static ulong Internal(ChessChallenge.API.Board board, int depth)
    {
        Span<ChessChallenge.API.Move> moves = stackalloc ChessChallenge.API.Move[128];

        if (depth == 1)
            return (ulong)board.GetLegalMoves(ref moves);
        
        ulong nodes = 0;
        
        int moveCount = board.GetLegalMoves(ref moves);
        
        for (int i = 0; i < moveCount; i++)
        {
            ChessChallenge.API.Move move = moves[i];
            board.MakeMove(move);
            nodes += Internal(board, depth - 1);
            board.UndoMove(move);
        }
        
        return nodes;
    }

}
```

### CODE REVIEW

**Comment by w1wwwwww** [comment]
see #109

**Comment by TheBlackPlague** [comment]
> see #109

Once again, that issue isn't relevant here as issue #188 actually showcases this being an actual problem, rather than just "oh, it could be faster so it should be".

**Comment by StevenChristy** [comment]
If I may offer a suggestion here. It may be that breaking existing bots is not acceptable in the middle of a challenge and since you are doing so out of self-interest then it could be perceived negatively. I recommend considering how you might make your improvement backwards compatible without impacting any existing bots negatively (minimal overhead). This would mean adding a separate function for the optimized call. I am assuming this is possible, but if it is not then please disregard the suggestion. I do like the idea of better performance would use the new api call in my own bots, but I don't like the idea of impacting anyone else.

**Comment by raklaptudirm** [comment]
@StevenChristy Will making a separate move generation function which takes a reference be better? Cause all existing bots will not be negatively impacted and those who want to make their engine faster can do so.

**Comment by StevenChristy** [comment]
Its a level playing field good bad and ugly. Faster is better but there are principles to consider. If one eliminates the strongest objections then they maximize the possibility of getting a yes instead of a no. Right now this is very likely to be rejected as it is not compatible with existing submissions. I don't believe the developer considered that in their approach to solving the problem. So I point it out, maybe it will improve the chances, maybe not.

**Comment by TheBlackPlague** [comment]
Sure, I'll edit this PR to make sure it's a separate function. Thank you for your insight. @StevenChristy

**Comment by SebLague** [comment]
Hi, I'm considering adding this is an alternative movegen function. I've made a test version in the Dev branch that makes sure that previous entries are not affected in any way. The new function in the Board class is called PopulateWithLegalMoves. One slight difference from the version in this PR is that it doesn't return the length and instead just slices the given span. Strangely I'm not really seeing much perf different between main and this pr on my machine, so would appreciate if you'd take a look at the dev branch and see if you're still seeing perf improvement there on your end?

**Comment by TheBlackPlague** [comment]
> Hi, I'm considering adding this is an alternative movegen function. I've made a test version in the Dev branch that makes sure that previous entries are not affected in any way. The new function in the Board class is called PopulateWithLegalMoves. One slight difference from the version in this PR is that it doesn't return the length and instead just slices the given span. Strangely I'm not really seeing much perf different between main and this pr on my machine, so would appreciate if you'd take a look at the dev branch and see if you're still seeing perf improvement there on your end?

Thank you for considering these changes, Sebastian. 

I have decided to run and test your branch, editing the SearchStackalloc method to see the difference between the two move generation techniques (GetLegalMoves & PopulateWithLegalMoves). 

Unfortunately, it came later to my attention that there are a few issues with the ways you are benchmarking: 
```cs
                System.Diagnostics.Stopwatch swInner = System.Diagnostics.Stopwatch.StartNew();

                ulong result = SearchStackalloc(depths[i]);
                if (result != expectedNodes[i])
                {
                    Console.WriteLine("Error");
                    break;
                }
                else
                {
                    Console.WriteLine(i + " successful: " + swInner.ElapsedMilliseconds + " ms");
                }
```
The above code does string concatenation before the Elapsed Milliseconds are concatenated into the code. Furthermore, the final output line: `Console.WriteLine("Time Total: " + sw.ElapsedMilliseconds + " ms.");` includes the time it takes to `LoadPosition` (which is a bunch of string parsing, an operation known to be slow).

As such, the results you see will be largely inconsistent with what you're expecting to see. In my benchmarks above, you may see me using the `Stopwatch.Stop()` method to ensure that no more milliseconds are elapsed during string concatenation (and otherwise handling). 

Regardless, fixing those benchmarking mistakes, I was still not fully happy with the performance difference I saw on my end:
```
Time Total: 3642 ms. (Stack Allocation)
Time Total: 5541 ms. (Heap Allocation)
```

I sense this is an issue with the low-depth criteria for the benchmark (at least for most of the data points), but I may be missing something. 

I believe that not slicing and returning the length is the better way to do this, but the `Slice()` operation is fast enough that it shouldn't cause an issue. The rest is up to you.

**Comment by audiBookning** [comment]
Just adding my random two cents.
First i don't really know if this change is really so much performant that it needs the change, but i do believe that the OP has reasonable arguments for it. Maybe adding some relevant tests would be needed to convince people of the changes.
To me, more performance is normally not to be despised in these type of situations but changes in the code just for performance reasons are often a drag if not backed by practical and testable reasons.

Is this change bringing so much differences that it give some people a edge over others?

Well if the problem is the API, one just has to remember that this is C# where function overloading exist for some time now 😉. So no API changes needed with backward combability problems.

And if some solutions can get benefits just from manipulating memory in an intelligent manner or even just from pure brute force, then they should be as interesting to see as any other solution based on many other reasons. And they should be in the competition's spirit (my interpretation) of solving a certain problem inside a limited resource space.

I mean. The prize is no gold cup. Most people should participate for things like "for the fun of it", the community or the intellectual challenge.

**Comment by SebLague** [comment]
This has now been added to v1.13. The new function is called GetLegalMovesNonAlloc. Thanks for the discussion everyone. And thanks @TheBlackPlague for the PR of course.

**Pull request closed without merging**
